# Generated by Django 4.2.7 on 2025-08-03 17:47

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Drug',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('ten_thuoc', models.CharField(max_length=255, verbose_name='Tên thuốc')),
                ('hoat_chat', models.TextField(blank=True, verbose_name='Hoạt chất')),
                ('phan_loai', models.CharField(blank=True, max_length=100, verbose_name='Phân loại')),
                ('nhom_thuoc', models.CharField(blank=True, max_length=100, verbose_name='Nhóm thuốc')),
                ('nuoc_dk', models.CharField(blank=True, max_length=100, verbose_name='Nước đăng ký')),
                ('source_data', models.URLField(blank=True, verbose_name='Nguồn dữ liệu')),
                ('source_pdf', models.URLField(blank=True, verbose_name='Nguồn PDF')),
                ('meta_data', models.CharField(blank=True, max_length=255, verbose_name='Meta data')),
                ('sys_id', models.CharField(blank=True, max_length=50, verbose_name='System ID')),
                ('sys_created_by', models.CharField(blank=True, max_length=100, verbose_name='Tạo bởi')),
                ('sys_updated_by', models.CharField(blank=True, max_length=100, verbose_name='Cập nhật bởi')),
                ('sys_created_on', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Ngày tạo')),
                ('sys_updated_on', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Ngày cập nhật')),
                ('sys_mod_count', models.CharField(blank=True, max_length=10, verbose_name='Số lần sửa đổi')),
                ('sys_tags', models.TextField(blank=True, verbose_name='Tags')),
            ],
            options={
                'verbose_name': 'Thuốc',
                'verbose_name_plural': 'Thuốc',
                'ordering': ['ten_thuoc'],
            },
        ),
        migrations.CreateModel(
            name='DrugInteraction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mechanism', models.TextField(verbose_name='Cơ chế tương tác')),
                ('consequence', models.TextField(verbose_name='Hậu quả')),
                ('management', models.TextField(verbose_name='Xử trí')),
                ('severity', models.CharField(choices=[('contraindicated', 'Chống chỉ định'), ('major', 'Tương tác nghiêm trọng'), ('moderate', 'Tương tác trung bình'), ('minor', 'Tương tác nhẹ')], default='moderate', max_length=20, verbose_name='Mức độ')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Ngày cập nhật')),
                ('drug1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interactions_as_drug1', to='drugs.drug', verbose_name='Thuốc 1')),
                ('drug2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interactions_as_drug2', to='drugs.drug', verbose_name='Thuốc 2')),
            ],
            options={
                'verbose_name': 'Tương tác thuốc',
                'verbose_name_plural': 'Tương tác thuốc',
                'ordering': ['-created_at'],
                'unique_together': {('drug1', 'drug2')},
            },
        ),
    ]
